# Generated by Django 4.0.1 on 2022-01-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="budget",
            old_name="author",
            new_name="user",
        ),
    ]
