# Generated by Django 4.0.1 on 2022-01-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_rename_author_budget_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='user',
            new_name='owner',
        ),
    ]
