# Generated by Django 4.0.1 on 2022-01-18 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0003_rename_user_budget_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
