# Generated by Django 4.0.1 on 2022-01-18 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0004_budget_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
